services:
  restaurant-service:
    build: .
    container_name: restaurant-service
    ports:
      - "3004:3004"
    env_file:
      - .env.docker
    networks:
      - backend

networks:
  backend:
    external: true